name: simo_personal_website
description: "Building my portfolio website in flutter"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_modular: ^5.0.3
  dio: ^5.4.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.13
  cupertino_icons: ^1.0.2
  custom_mouse_cursor: ^1.1.0
  url_launcher: ^6.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mocktail: ^0.3.0
  modular_test: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo/disco2.png
    - assets/images/logo/S-logo-full.png
    - assets/images/logo/s-logo-no-bg-crop.png
    - assets/images/logo/S-no-border.png
    - assets/images/logo/S-no-border-small.png

    - assets/images/icons/icons8-twitter-96.png
    - assets/images/icons/icons8-facebook-96.png
    - assets/images/icons/icons8-at-sign-96.png
    - assets/images/icons/icons8-google-96.png
    - assets/images/icons/PDP2.png
    - assets/images/icons/STARTUP.png
    - assets/images/icons/WORK.png

    - assets/images/logo/pattern3.png
    - assets/images/logo/kotlin-logo.png
    - assets/images/logo/pattern5.png
    - assets/images/logo/pattern2.png
    - assets/images/logo/android-logo-selected.png
    - assets/images/logo/Java-logo.png
    - assets/images/logo/Architecture.png
    - assets/images/logo/pattern6.png
    - assets/images/logo/node-js.png
    - assets/images/logo/pattern4.png
    - assets/images/logo/pattern7.png
    - assets/images/logo/pattern1.png
    - assets/images/logo/flutter.png
    - assets/images/logo/under-construction.png
    - assets/images/logo/under-construction-worker.png
    - assets/images/logo/pdf-logo.png

    - assets/images/Simo.jpeg
    - assets/images/contact-card.png

    - assets/images/companies/absa.png
    - assets/images/companies/discovery.png
    - assets/images/companies/dvt.png
    - assets/images/companies/fidelitech-logo.png
    - assets/images/companies/mukuru.png
    - assets/images/companies/mukuru-big.png
    - assets/images/companies/reverside.png
    - assets/images/companies/reverside-big.png
    - assets/images/companies/standard-bank-logo.png
    - assets/images/companies/vitality-logo.png

    - assets/pdf/matric_certificate.pdf
    - assets/pdf/onesimo_nyathi_cv_2024.pdf
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-VariableFont_wght.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Black.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat/Montserrat-ExtraBold.ttf
        - asset: assets/fonts/Montserrat/Montserrat-ExtraLight.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Thin.ttf
        - asset: assets/fonts/Montserrat/Montserrat-VariableFont_wght.ttf
#          weight: 400

    - family: Crimson_Text
      fonts:
        - asset: assets/fonts/Crimson_Text/CrimsonText-Bold.ttf
        - asset: assets/fonts/Crimson_Text/CrimsonText-Regular.ttf
        - asset: assets/fonts/Crimson_Text/CrimsonText-SemiBold.ttf
#          weight: 400

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
