name: simo_personal_website
description: "Building my portfolio website in flutter"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_modular: ^5.0.3
  dio: ^5.4.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.13
  cupertino_icons: ^1.0.2
  custom_mouse_cursor: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mocktail: ^0.3.0
  modular_test: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/logo/disco2.png
    - images/logo/S-logo-full.png
    - images/logo/s-logo-no-bg-crop.png
    - images/logo/S-no-border.png
    - images/logo/S-no-border-small.png

    - images/icons/icons8-twitter-96.png
    - images/icons/icons8-facebook-96.png
    - images/icons/icons8-at-sign-96.png
    - images/icons/icons8-google-96.png

    - images/logo/pattern3.png
    - images/logo/kotlin-logo.png
    - images/logo/pattern5.png
    - images/logo/pattern2.png
    - images/logo/android-logo-selected.png
    - images/logo/Java-logo.png
    - images/logo/Architecture.png
    - images/logo/pattern6.png
    - images/logo/node-js.png
    - images/logo/pattern4.png
    - images/logo/pattern7.png
    - images/logo/pattern1.png
    - images/logo/flutter.png

    - images/Simo.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat/Montserrat-Italic-VariableFont_wght.ttf
          style: italic
        - asset: fonts/Montserrat/Montserrat-VariableFont_wght.ttf
        - asset: fonts/Montserrat/Montserrat-Black.ttf
        - asset: fonts/Montserrat/Montserrat-BlackItalic.ttf
        - asset: fonts/Montserrat/Montserrat-Bold.ttf
        - asset: fonts/Montserrat/Montserrat-BoldItalic.ttf
        - asset: fonts/Montserrat/Montserrat-ExtraBold.ttf
        - asset: fonts/Montserrat/Montserrat-ExtraBoldItalic.ttf
        - asset: fonts/Montserrat/Montserrat-ExtraLight.ttf
        - asset: fonts/Montserrat/Montserrat-ExtraLightItalic.ttf
        - asset: fonts/Montserrat/Montserrat-Italic.ttf
        - asset: fonts/Montserrat/Montserrat-Light.ttf
        - asset: fonts/Montserrat/Montserrat-LightItalic.ttf
        - asset: fonts/Montserrat/Montserrat-Medium.ttf
        - asset: fonts/Montserrat/Montserrat-MediumItalic.ttf
        - asset: fonts/Montserrat/Montserrat-Regular.ttf
        - asset: fonts/Montserrat/Montserrat-SemiBold.ttf
        - asset: fonts/Montserrat/Montserrat-SemiBoldItalic.ttf
        - asset: fonts/Montserrat/Montserrat-Thin.ttf
        - asset: fonts/Montserrat/Montserrat-ThinItalic.ttf
        - asset: fonts/Montserrat/Montserrat-VariableFont_wght.ttf

    - family: Crimson_Text
      fonts:
        - asset: fonts/Crimson_Text/CrimsonText-Bold.ttf
        - asset: fonts/Crimson_Text/CrimsonText-BoldItalic.ttf
        - asset: fonts/Crimson_Text/CrimsonText-Italic.ttf
        - asset: fonts/Crimson_Text/CrimsonText-Regular.ttf
        - asset: fonts/Crimson_Text/CrimsonText-SemiBold.ttf
        - asset: fonts/Crimson_Text/CrimsonText-SemiBoldItalic.ttf
          weight: 700

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
